In [1]:
import joblib

In [ ]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import cross_val_score, KFold, StratifiedKFold
from sklearn.pipeline import Pipeline


from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
cdc_diabetes_health_indicators = fetch_ucirepo(id=891) 
  
# data (as pandas dataframes) 
X = cdc_diabetes_health_indicators.data.features 
y = cdc_diabetes_health_indicators.data.targets 


ls = X[X.columns[:3]].values

X = X.values
y = np.ravel(y)



logistic = Pipeline(steps=[('scaler', StandardScaler()),
                            ('model', LogisticRegression(max_iter=200))])

params = {
    "model__tol": np.logspace(-5, -2, 50),
    "model__C": np.logspace(-4, 4, 50),
    "model__l1_ratio": [0,1],
    "model__solver": ['saga'],
    "model__class_weight": ["balanced", {0:0.15, 1:0.85},{0: 0.2, 1: 0.8}, {0:0.3, 1:0.7}],
    "model__max_iter": [100, 200, 500]
}

kf = StratifiedKFold(n_splits= 5, shuffle=True, random_state=12)

logreg_cv = RandomizedSearchCV(logistic, params, cv=kf, random_state=12, n_iter=30, scoring='f1', n_jobs=-1, refit=True)

X_train, X_test , y_train, y_test = train_test_split( X, y, test_size=0.3, random_state=12)

logreg_cv.fit(X_train, y_train)

In [24]:
ls = X[X.columns[:3]].values
ls.shape

array([[1, 1, 1],
       [0, 0, 0],
       [1, 1, 1],
       ...,
       [0, 0, 1],
       [1, 0, 1],
       [1, 1, 1]], shape=(253680, 3))

In [30]:
features=list(X.columns)
features

['HighBP',
 'HighChol',
 'CholCheck',
 'BMI',
 'Smoker',
 'Stroke',
 'HeartDiseaseorAttack',
 'PhysActivity',
 'Fruits',
 'Veggies',
 'HvyAlcoholConsump',
 'AnyHealthcare',
 'NoDocbcCost',
 'GenHlth',
 'MentHlth',
 'PhysHlth',
 'DiffWalk',
 'Sex',
 'Age',
 'Education',
 'Income']

In [3]:
joblib.dump(logreg_cv, 'logreg_cv.joblib')

NameError: name 'logreg_cv' is not defined

In [16]:
X.columns

Index(['HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker', 'Stroke',
       'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies',
       'HvyAlcoholConsump', 'AnyHealthcare', 'NoDocbcCost', 'GenHlth',
       'MentHlth', 'PhysHlth', 'DiffWalk', 'Sex', 'Age', 'Education',
       'Income'],
      dtype='str')

In [42]:
lamb=X.values[-1:]
lamb.shape

(1, 21)

In [21]:
logreg_cv=joblib.load('logreg_cv.joblib')

In [25]:
import random
X_test = X.sample(1)
X_test = X_test.values
print(X_test)
X_test.shape

[[ 1  1  1 45  0  0  0  1  1  1  0  1  0  3 10 30  1  0  7  6  8]]


(1, 21)

In [44]:
y_pred = logreg_cv.predict(lamb)[0]
print(y_pred)

# print(logreg_cv.score(X_test, y_test))

# print(y_pred)

0


In [6]:
X_test[-1]

array([ 1,  0,  1, 28,  0,  0,  0,  0,  0,  1,  0,  1,  0,  3,  0, 30,  0,
        1, 10,  6,  8])